from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from database.base import Base


# One row per WhatsApp invite link generated by the couple. Public lookup by
# token only — display-name personalization for the envelope page, never an
# auth mechanism (see docs/PRODUCT_DECISIONS.md §8: passwordless login is
# explicitly out of scope for this phase).
class InviteLink(Base):
    __tablename__ = "invite_links"

    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(64), unique=True, index=True, nullable=False)
    first_name = Column(String(80), nullable=False)
    last_name = Column(String(80), nullable=False)
    created_at = Column(DateTime, nullable=False)
    # Set the first time this invite's guest confirms/recovers access — lets
    # a repeat visit reuse the same guest User instead of creating another.
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=True, index=True)

    user = relationship("User")
