from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from database.base import Base


# One row per WhatsApp invite link generated by the couple. The token drives
# both the envelope page's display-name personalization and the passwordless
# first RSVP confirmation, which creates the guest's account and binds it here
# (see services/guest_access_service.py).
class InviteLink(Base):
    __tablename__ = "invite_links"

    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(64), unique=True, index=True, nullable=False)
    first_name = Column(String(80), nullable=False)
    last_name = Column(String(80), nullable=False)
    created_at = Column(DateTime, nullable=False)
    # Set the first time this invite's guest confirms/recovers access — lets
    # a repeat visit reuse the same guest User instead of creating another.
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=True, index=True)

    user = relationship("User")
